In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_dir = Path("../data/raw/bts/2025/01")

list(data_dir.glob("*.csv"))

[WindowsPath('../data/raw/bts/2025/01/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv')]

In [3]:
csv_file = list(data_dir.glob("*.csv"))[0]

df = pd.read_csv(csv_file)

C:\Users\Админ\AppData\Local\Temp\ipykernel_9556\3855228934.py:3: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(csv_file)

In [4]:
df.shape

(539747, 110)

In [5]:
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2025,1,1,1,3,2025-01-01,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,2,4,2025-01-02,AA,19805,AA,N110AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,5,2025-01-03,AA,19805,AA,N106NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,1,1,4,6,2025-01-04,AA,19805,AA,N117AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,5,7,2025-01-05,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [7]:
df.dtypes

Year                  int64
Quarter               int64
Month                 int64
DayofMonth            int64
DayOfWeek             int64
                     ...
Div5TotalGTime      float64
Div5LongestGTime    float64
Div5WheelsOff       float64
Div5TailNum         float64
Unnamed: 109        float64
Length: 110, dtype: object

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 453.0 MB

In [9]:
df.isna().sum().sort_values(ascending=False).head(30)

Div5WheelsOn        539747
Div5TotalGTime      539747
Div5LongestGTime    539747
Div5WheelsOff       539747
Div5TailNum         539747
Div5Airport         539747
Unnamed: 109        539747
Div4TailNum         539747
Div4WheelsOff       539747
Div4LongestGTime    539747
Div4TotalGTime      539747
Div4WheelsOn        539747
Div4AirportSeqID    539747
Div4AirportID       539747
Div5AirportID       539747
Div5AirportSeqID    539747
Div3WheelsOff       539747
Div3LongestGTime    539747
Div3TotalGTime      539747
Div3WheelsOn        539747
Div3AirportSeqID    539747
Div3Airport         539747
Div4Airport         539747
Div3TailNum         539747
Div3AirportID       539747
Div2WheelsOff       539743
Div2TailNum         539743
Div2Airport         539724
Div2AirportSeqID    539724
Div2TotalGTime      539724
dtype: int64

In [10]:
needed_columns = [
    "Origin",
    "FlightDate",
    "Reporting_Airline",
    "Flight_Number_Reporting_Airline",
    "CRSDepTime",
    "DepTime",
    "DepDelay",
    "DepDel15",
    "Cancelled",
    "Diverted",
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay"
]

[col for col in needed_columns if col not in df.columns]

[]

In [11]:
jfk = df[df["Origin"] == "JFK"].copy()

jfk.shape

(8327, 110)

In [12]:
jfk.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2025,1,1,1,3,2025-01-01,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,2,4,2025-01-02,AA,19805,AA,N110AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,5,2025-01-03,AA,19805,AA,N106NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,1,1,4,6,2025-01-04,AA,19805,AA,N117AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,5,7,2025-01-05,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
len(jfk)

8327

In [14]:
completed_jfk = jfk[jfk["Cancelled"] == 0]

len(completed_jfk)

8181

In [15]:
delayed_jfk = completed_jfk[completed_jfk["DepDel15"] == 1]

len(delayed_jfk)

1399

In [16]:
delay_share = len(delayed_jfk) / len(completed_jfk) * 100

delay_share

17.10059894878377

In [17]:
daily_stats = (
    jfk[jfk["Cancelled"] == 0]
    .groupby("FlightDate")
    .agg(
        flights=("FlightDate", "size"),
        delayed_flights=("DepDel15", "sum")
    )
    .reset_index()
)

daily_stats["delay_share"] = (
    daily_stats["delayed_flights"] / daily_stats["flights"] * 100
)

daily_stats.head()

   FlightDate  flights  delayed_flights  delay_share
0  2025-01-01      267             50.0    18.726592
1  2025-01-02      298             44.0    14.765101
2  2025-01-03      296             56.0    18.918919
3  2025-01-04      288             74.0    25.694444
4  2025-01-05      302            107.0    35.430464